youtube-dl-front:
    image: enriquek/youtube-dl-front
    container_name: youtube-dl-front
    ports:
      - 3000:3000
    volumes:
      - /opt/youtube-dl-front/videos:/youtube-dl-front/server/videos
      - /opt/youtube-dl-front/music:/youtube-dl-front/server/music
      - /opt/youtube-dl-front/config/database.json:/youtube-dl-front/config/database.json:rw
